/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vng.zing.pusheventmessage.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum GetEventMsgResultCode implements org.apache.thrift.TEnum {
  SUCCESS(0),
  OUT_OF_DATE(1),
  PLATFORM_NOT_MATCH(2),
  BUNDLE_ID_NOT_MATCH(3),
  PACKAGE_NAME_NOT_MATCH(4),
  GUID_NOT_MATCH(5),
  SDK_VERSION_NOT_MATCH(6),
  APP_VERSION_NOTMATCH(7),
  VIEW_LIMITED(8),
  NOT_ANY_MSG(9);

  private final int value;

  private GetEventMsgResultCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GetEventMsgResultCode findByValue(int value) { 
    switch (value) {
      case 0:
        return SUCCESS;
      case 1:
        return OUT_OF_DATE;
      case 2:
        return PLATFORM_NOT_MATCH;
      case 3:
        return BUNDLE_ID_NOT_MATCH;
      case 4:
        return PACKAGE_NAME_NOT_MATCH;
      case 5:
        return GUID_NOT_MATCH;
      case 6:
        return SDK_VERSION_NOT_MATCH;
      case 7:
        return APP_VERSION_NOTMATCH;
      case 8:
        return VIEW_LIMITED;
      case 9:
        return NOT_ANY_MSG;
      default:
        return null;
    }
  }
}
