/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vng.zing.pusheventmessage.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class GetLastRequestResult implements org.apache.thrift.TBase<GetLastRequestResult, GetLastRequestResult._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetLastRequestResult");

  private static final org.apache.thrift.protocol.TField RESULT_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("resultCode", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField EVENT_MSG_REQUESTS_FIELD_DESC = new org.apache.thrift.protocol.TField("eventMsgRequests", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new GetLastRequestResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new GetLastRequestResultTupleSchemeFactory());
  }

  public int resultCode; // required
  public List<EventMsgRequestInfo> eventMsgRequests; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESULT_CODE((short)1, "resultCode"),
    EVENT_MSG_REQUESTS((short)2, "eventMsgRequests");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESULT_CODE
          return RESULT_CODE;
        case 2: // EVENT_MSG_REQUESTS
          return EVENT_MSG_REQUESTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RESULTCODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESULT_CODE, new org.apache.thrift.meta_data.FieldMetaData("resultCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.EVENT_MSG_REQUESTS, new org.apache.thrift.meta_data.FieldMetaData("eventMsgRequests", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EventMsgRequestInfo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetLastRequestResult.class, metaDataMap);
  }

  public GetLastRequestResult() {
  }

  public GetLastRequestResult(
    int resultCode,
    List<EventMsgRequestInfo> eventMsgRequests)
  {
    this();
    this.resultCode = resultCode;
    setResultCodeIsSet(true);
    this.eventMsgRequests = eventMsgRequests;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GetLastRequestResult(GetLastRequestResult other) {
    __isset_bitfield = other.__isset_bitfield;
    this.resultCode = other.resultCode;
    if (other.isSetEventMsgRequests()) {
      List<EventMsgRequestInfo> __this__eventMsgRequests = new ArrayList<EventMsgRequestInfo>();
      for (EventMsgRequestInfo other_element : other.eventMsgRequests) {
        __this__eventMsgRequests.add(new EventMsgRequestInfo(other_element));
      }
      this.eventMsgRequests = __this__eventMsgRequests;
    }
  }

  public GetLastRequestResult deepCopy() {
    return new GetLastRequestResult(this);
  }

  @Override
  public void clear() {
    setResultCodeIsSet(false);
    this.resultCode = 0;
    this.eventMsgRequests = null;
  }

  public int getResultCode() {
    return this.resultCode;
  }

  public GetLastRequestResult setResultCode(int resultCode) {
    this.resultCode = resultCode;
    setResultCodeIsSet(true);
    return this;
  }

  public void unsetResultCode() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RESULTCODE_ISSET_ID);
  }

  /** Returns true if field resultCode is set (has been assigned a value) and false otherwise */
  public boolean isSetResultCode() {
    return EncodingUtils.testBit(__isset_bitfield, __RESULTCODE_ISSET_ID);
  }

  public void setResultCodeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RESULTCODE_ISSET_ID, value);
  }

  public int getEventMsgRequestsSize() {
    return (this.eventMsgRequests == null) ? 0 : this.eventMsgRequests.size();
  }

  public java.util.Iterator<EventMsgRequestInfo> getEventMsgRequestsIterator() {
    return (this.eventMsgRequests == null) ? null : this.eventMsgRequests.iterator();
  }

  public void addToEventMsgRequests(EventMsgRequestInfo elem) {
    if (this.eventMsgRequests == null) {
      this.eventMsgRequests = new ArrayList<EventMsgRequestInfo>();
    }
    this.eventMsgRequests.add(elem);
  }

  public List<EventMsgRequestInfo> getEventMsgRequests() {
    return this.eventMsgRequests;
  }

  public GetLastRequestResult setEventMsgRequests(List<EventMsgRequestInfo> eventMsgRequests) {
    this.eventMsgRequests = eventMsgRequests;
    return this;
  }

  public void unsetEventMsgRequests() {
    this.eventMsgRequests = null;
  }

  /** Returns true if field eventMsgRequests is set (has been assigned a value) and false otherwise */
  public boolean isSetEventMsgRequests() {
    return this.eventMsgRequests != null;
  }

  public void setEventMsgRequestsIsSet(boolean value) {
    if (!value) {
      this.eventMsgRequests = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESULT_CODE:
      if (value == null) {
        unsetResultCode();
      } else {
        setResultCode((Integer)value);
      }
      break;

    case EVENT_MSG_REQUESTS:
      if (value == null) {
        unsetEventMsgRequests();
      } else {
        setEventMsgRequests((List<EventMsgRequestInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESULT_CODE:
      return Integer.valueOf(getResultCode());

    case EVENT_MSG_REQUESTS:
      return getEventMsgRequests();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESULT_CODE:
      return isSetResultCode();
    case EVENT_MSG_REQUESTS:
      return isSetEventMsgRequests();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof GetLastRequestResult)
      return this.equals((GetLastRequestResult)that);
    return false;
  }

  public boolean equals(GetLastRequestResult that) {
    if (that == null)
      return false;

    boolean this_present_resultCode = true;
    boolean that_present_resultCode = true;
    if (this_present_resultCode || that_present_resultCode) {
      if (!(this_present_resultCode && that_present_resultCode))
        return false;
      if (this.resultCode != that.resultCode)
        return false;
    }

    boolean this_present_eventMsgRequests = true && this.isSetEventMsgRequests();
    boolean that_present_eventMsgRequests = true && that.isSetEventMsgRequests();
    if (this_present_eventMsgRequests || that_present_eventMsgRequests) {
      if (!(this_present_eventMsgRequests && that_present_eventMsgRequests))
        return false;
      if (!this.eventMsgRequests.equals(that.eventMsgRequests))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(GetLastRequestResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    GetLastRequestResult typedOther = (GetLastRequestResult)other;

    lastComparison = Boolean.valueOf(isSetResultCode()).compareTo(typedOther.isSetResultCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResultCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resultCode, typedOther.resultCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEventMsgRequests()).compareTo(typedOther.isSetEventMsgRequests());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEventMsgRequests()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.eventMsgRequests, typedOther.eventMsgRequests);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GetLastRequestResult(");
    boolean first = true;

    sb.append("resultCode:");
    sb.append(this.resultCode);
    first = false;
    if (!first) sb.append(", ");
    sb.append("eventMsgRequests:");
    if (this.eventMsgRequests == null) {
      sb.append("null");
    } else {
      sb.append(this.eventMsgRequests);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GetLastRequestResultStandardSchemeFactory implements SchemeFactory {
    public GetLastRequestResultStandardScheme getScheme() {
      return new GetLastRequestResultStandardScheme();
    }
  }

  private static class GetLastRequestResultStandardScheme extends StandardScheme<GetLastRequestResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GetLastRequestResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESULT_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.resultCode = iprot.readI32();
              struct.setResultCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // EVENT_MSG_REQUESTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list72 = iprot.readListBegin();
                struct.eventMsgRequests = new ArrayList<EventMsgRequestInfo>(_list72.size);
                for (int _i73 = 0; _i73 < _list72.size; ++_i73)
                {
                  EventMsgRequestInfo _elem74; // required
                  _elem74 = new EventMsgRequestInfo();
                  _elem74.read(iprot);
                  struct.eventMsgRequests.add(_elem74);
                }
                iprot.readListEnd();
              }
              struct.setEventMsgRequestsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GetLastRequestResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(RESULT_CODE_FIELD_DESC);
      oprot.writeI32(struct.resultCode);
      oprot.writeFieldEnd();
      if (struct.eventMsgRequests != null) {
        oprot.writeFieldBegin(EVENT_MSG_REQUESTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.eventMsgRequests.size()));
          for (EventMsgRequestInfo _iter75 : struct.eventMsgRequests)
          {
            _iter75.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GetLastRequestResultTupleSchemeFactory implements SchemeFactory {
    public GetLastRequestResultTupleScheme getScheme() {
      return new GetLastRequestResultTupleScheme();
    }
  }

  private static class GetLastRequestResultTupleScheme extends TupleScheme<GetLastRequestResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GetLastRequestResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetResultCode()) {
        optionals.set(0);
      }
      if (struct.isSetEventMsgRequests()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetResultCode()) {
        oprot.writeI32(struct.resultCode);
      }
      if (struct.isSetEventMsgRequests()) {
        {
          oprot.writeI32(struct.eventMsgRequests.size());
          for (EventMsgRequestInfo _iter76 : struct.eventMsgRequests)
          {
            _iter76.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GetLastRequestResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.resultCode = iprot.readI32();
        struct.setResultCodeIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list77 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.eventMsgRequests = new ArrayList<EventMsgRequestInfo>(_list77.size);
          for (int _i78 = 0; _i78 < _list77.size; ++_i78)
          {
            EventMsgRequestInfo _elem79; // required
            _elem79 = new EventMsgRequestInfo();
            _elem79.read(iprot);
            struct.eventMsgRequests.add(_elem79);
          }
        }
        struct.setEventMsgRequestsIsSet(true);
      }
    }
  }

}

