/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vng.zing.pusheventmessage.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PushNotiJobStatus implements org.apache.thrift.TEnum {
  PEND(1),
  PROCESS(2),
  PAUSE(3),
  COMPLETE(4);

  private final int value;

  private PushNotiJobStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PushNotiJobStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return PEND;
      case 2:
        return PROCESS;
      case 3:
        return PAUSE;
      case 4:
        return COMPLETE;
      default:
        return null;
    }
  }
}
